### ISSUE TITLE
support camelCase

### ISSUE THREAD

**Issue by Lighting-Jack** [TeamSupercell/typings-for-css-modules-loader#40]
Expect:
```css
.foo {
  color: white;
}

.bar-baz {
  color: green;
}
```
```javascript
export const foo: string;
export const barBaz: string;
```
